import Head from "next/head";
import Banner from "@/components/banner/banner";
import Cards from "@/components/cards/cards";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <title>Vidflex</title>
      </Head>
      <Banner
        title="PEAKY BLINDERS"
        subTitle="Tommy Shelby, a dangerous man, leads the Peaky Blinders, a gang based
in Birmingham. Soon, Chester Campbell, an inspector, decides to nab him
and put an end to the criminal activities."
        imgUrl="https://rare-gallery.com/uploads/posts/538616-peaky-blinders.jpg"
      />
      <div className="cards-wrapper">
        <Cards title="Disney" size="large" />
        <Cards title="Action" />
        <Cards title="Action" size="small" />
      </div>
    </>
  );
}
