import Head from "next/head";
import Banner from "@/components/banner/banner";
import Cards from "@/components/cards/cards";
import { getVideos } from "@/lib/videos";
import { videos } from "@/data/videos";

export default function Home() {
	const videosData = getVideos();
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
				<title>Vidflex</title>
			</Head>
			<Banner
				title={videosData[0].title}
				subTitle="Tommy Shelby, a dangerous man, leads the Peaky Blinders, a gang based
in Birmingham. Soon, Chester Campbell, an inspector, decides to nab him
and put an end to the criminal activities."
				imgUrl={videosData[0].imgUrl}
			/>
			<div className="cards-wrapper">
				<Cards videos={videosData} size="large" title="Movies" />
				<Cards videos={videosData} title="Movies" />
				<Cards videos={videosData} size="small" title="Movies" />
			</div>
		</>
	);
}
